url: 'https://apiuat.rockfintech.com/2.0.0/deposit'
rft_token: ''
rft_org: '1001'
rft_key: '6615252261684528'
rft_secret: '594a014caa7641279becaea0386660fc'
private_key: |
  -----BEGIN PRIVATE KEY-----
  MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCdVDID9A8BxVvQ
  HbaEatSc5AkbzOw9+jiujlJ0IrJukhFtNQTBvkXNX5KxNS0wxTxjd3Tq3+pVKvER
  aHOJn6teRoaptXz8ACrqElVi6iTK9cvwohb87w8LkcTJdUqBo/DZnREkjxfU0rUQ
  qOm/SSLzgKNgNWCgvCNlcTyXa3yFZGXRb25Rbd7oCEzud1Rj+WO9HYG2kVZALHeb
  w/M6wambFYX5q4TGdURYP9cYiVshzlEQzBSioLXQmzdex79iLxH8pLB8HQdhyWS2
  5VKQx1Rq+SC5lUvVnZRIZ41A7D7OuXrVyzxa9hIoVp5mPeH3wvyPNc3H8UVMRGlT
  Z6OY6DLHAgMBAAECggEAVDQv4LXLImOC1ExS12RmDuJtjZeMCU/W7nX143p+jXdY
  JF7wANHZgiXY2UdgvG2T+JiC1wKo5JRrGaoRzGLM0VRl1obwMd/VGBpf4OT4dDhB
  wrS+IPnBz6tg64H/MouP6KiL+EkttBZiGlyNXnfCYRlEV8W5xc1sFGsaxuAccTeI
  A7gUFDUKpTxTV5yHWQADKMAx2qbUY13xOOZvVm2al6Fq6qimnW7VF5hLB0/P2mHR
  GqdAt3UhNieaWTea8rNIjhKJEggCUHGOFqr6N7lnmN11MA6zYrLpic9LofoNTW+f
  LnrI93VsPLw1K8yITwpxZHnC61hiT64jDrcRe6LBAQKBgQDJVQfINa34CuNpZ6M0
  Gr6aKCcUkzL8XQhqbjRmu1aEt1t0c9gxOF6Kik1YBxGy5Fjnfo9UEe7ozNE5wlJk
  2PdCJJATMe/ct7t8J5LC8bKqTRbuHDyDUC0oJGK+SOZUyKMu2LCeY8tJHV8iWKgo
  dDmbAvrbLyfA6jraDP2YWHDjYQKBgQDIDGq+r/y//YcIsNbgv9G/RVsgMR0jqI+n
  xG/BTYx51ZjTzn3s5QRnI6Zl9ujY8sxL9yDY+witMubcD8JsiB8ekdjU9UXrobSz
  +vO7tqSQwo7OLVTJrcSlCLdvO7YLma8XqHxzCMhgGtDRcdpbvyFU08LZVg4rMhGY
  36L/4C7vJwKBgGeTqzFBDIMzdtNfUgMYTz6XsaNQJ0bVxeKbV7ISZuxYOGCsyGhq
  C5lSlX/YAy75cxOFdM9XeoWh+XGxmxnu1SXeEZEOe8wdagLxiPtpxPUAO++77xXP
  RawFLBehAX5Uyj7rk9GonYi755mP6tMFGC27Vrs0g0soNabAUCb0OP+BAoGAYR0e
  CNoYYf+quP5YIh0crrT1qugM1E21B2WmNvn1kwOtQE2C9iirfYJh+ifmG8Oqh8o9
  qPgc2y/VwMjpwpRGPyngUGmNevkyZxkRj3P36cp5Vv/MpGd2CgP0QMyE8Ja32E1T
  tOhzlawO6U5TCaz8eliew7EyCagxwLv4Pi1Pu4sCgYBmE2YGh5uh2q6OidaP7xHq
  2IPiT4yD4eSF8MLiGssHyeqPfnWuCV6c2TaT79ibSkopLTJYYbkq9Pm3sV7KXCJa
  cCD0I7x8NJtcsUZb7OTAn3Mm0MRQ1peCtFJrWpRMn2vHHdxklNRyIOaZBToonhEI
  zDCutU9OtlrUP6WoyIZ0iA==
  -----END PRIVATE KEY-----
public_key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArIEJRYUYtYUFIVXxRkw3
  vw4Bt8xqwySmIG9Iou1S0+i7xXzchpIR/kid1L9kJJGfk6bd6451RU+eEcaeI08B
  OutsVidca051/PnkTRZl7S+Tpwau6TSUFfAMFNEYwFkuvmqGbm/EqyN0Mb0wZz7s
  vmJIE6iKhgv+rGVkmXaAQQsu1f5erXKM4M6ukWSwIuStOGjgn33PK7s4TUwQK9Ay
  q0QgJyT3j/WRjy8nB/D8plnitl/SI5VR7xsMkpy2giovYtp4LvFV5QOFSYobqiP2
  Te0a93ey7H2IAXOBveTCihr+d3jaAh2Qdj+Lfu7UaqtdpTjR0zN707G7HPVTRXLz
  bQIDAQAB
  -----END PUBLIC KEY-----
